In [1]:
import numpy as np

In [271]:
X=np.array([[11,2],[100,20]])

In [272]:
xCov=np.cov(X)

In [273]:
xCov

array([[  40.5,  360. ],
       [ 360. , 3200. ]])

In [274]:
eigvals, eigvecs=np.linalg.eig(xCov)

In [275]:
eigvecs

array([[-0.99373132, -0.11179477],
       [ 0.11179477, -0.99373132]])

In [276]:
eigvals

array([   0. , 3240.5])

In [277]:
eiganPairs=[[i[0],i[1]] for i in zip(eigvals, eigvecs)]

In [278]:
eiganPairs

[[0.0, array([-0.99373132, -0.11179477])],
 [3240.5, array([ 0.11179477, -0.99373132])]]

In [279]:
eiganPairSorted=[i for i in sorted(eiganPairs, key=lambda x: x[0], reverse=True)]

In [280]:
W=np.array([i[1] for i in eiganPairSorted])


In [281]:
W

array([[ 0.11179477, -0.99373132],
       [-0.99373132, -0.11179477]])

In [282]:
X

array([[ 11,   2],
       [100,  20]])

In [283]:
Z=X @ W

In [284]:
Z

array([[  -0.75772013,  -11.15463402],
       [  -8.69514902, -101.60902708]])

In [285]:
pcaZ=np.array([[i[0] for i in Z]])

In [286]:
pcaZ

array([[-0.75772013, -8.69514902]])

### You can reconstruct to original X from Z, not from pcaZ

In [287]:
V=np.linalg.inv(W)

In [288]:
reconstructedX=Z @ V

In [289]:
reconstructedX

array([[ 11.,   2.],
       [100.,  20.]])